package com.creditharmony.core.fortune.dao;

import java.util.List;

import com.creditharmony.core.fortune.entity.BilldayCfgEntity;
import com.creditharmony.core.persistence.annotation.CoreBatisDao;

/**
 * 结算日账单日配置表-Dao
 * 
 * @Class Name BilldayCfgDao
 * @author 周亮
 * @Create In 2016年01月01日
 */
@CoreBatisDao
public interface BilldayCfgDao {
	
	/**
	 * 检索结算日账单日配置
	 * 
	 * @param  key		
	 * @return List<BilldayCfgEntity> 检索结果
	 */
	public List<BilldayCfgEntity> selBilldayCfg(BilldayCfgEntity key);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz.t_tz_billday_cfg
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
	public int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz.t_tz_billday_cfg
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
	public int insert(BilldayCfgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz.t_tz_billday_cfg
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
	public int insertSelective(BilldayCfgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz.t_tz_billday_cfg
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
	public int updateByPrimaryKeySelective(BilldayCfgEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tz.t_tz_billday_cfg
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
	public int updateByPrimaryKey(BilldayCfgEntity record);
}