package com.creditharmony.core.fortune.entity;

import java.util.Date;

/**
 * 结算日账单日配置表-Entity
 * 
 * @Class Name BilldayCfgEntity
 * @author 周亮
 * @Create In 2016年01月01日
 */
public class BilldayCfgEntity {
	
    /** 年 */
    private Integer year;
    /** 结算月 */
    private Integer settleMonth;
    /** 结算日 */
    private Integer settleDay;
    /** 结算日期 */
    private Date settleDate;
    /** 账单月 */
    private Integer billMonth;
    /** 账单日 */
    private Integer billDay;
    /** 账单日期 */
    private Date billDate;
    /** 出借编号 */
    private String lendCode;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tz.t_tz_billday_cfg.year
     *
     * @return the value of tz.t_tz_billday_cfg.year
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tz.t_tz_billday_cfg.year
     *
     * @param year the value for tz.t_tz_billday_cfg.year
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tz.t_tz_billday_cfg.month
     *
     * @return the value of tz.t_tz_billday_cfg.month
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public Integer getMonth() {
        return settleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tz.t_tz_billday_cfg.month
     *
     * @param month the value for tz.t_tz_billday_cfg.month
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public void setMonth(Integer settleMonth) {
        this.settleMonth = settleMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tz.t_tz_billday_cfg.settle_day
     *
     * @return the value of tz.t_tz_billday_cfg.settle_day
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public Integer getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tz.t_tz_billday_cfg.settle_day
     *
     * @param settleDay the value for tz.t_tz_billday_cfg.settle_day
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public void setSettleDay(Integer settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tz.t_tz_billday_cfg.bill_day
     *
     * @return the value of tz.t_tz_billday_cfg.bill_day
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public Integer getBillDay() {
        return billDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tz.t_tz_billday_cfg.bill_day
     *
     * @param billDay the value for tz.t_tz_billday_cfg.bill_day
     *
     * @mbggenerated Wed May 04 15:22:00 CST 2016
     */
    public void setBillDay(Integer billDay) {
        this.billDay = billDay;
    }

	/**
	 * @return the lendCode
	 */
	public String getLendCode() {
		return lendCode;
	}

	/**
	 * @param lendCode the lendCode to set
	 */
	public void setLendCode(String lendCode) {
		this.lendCode = lendCode;
	}

	/**
	 * @return the billDate
	 */
	public Date getBillDate() {
		return billDate;
	}

	/**
	 * @param billDate the billDate to set
	 */
	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	/**
	 * @return the settleDate
	 */
	public Date getSettleDate() {
		return settleDate;
	}

	/**
	 * @param settleDate the settleDate to set
	 */
	public void setSettleDate(Date settleDate) {
		this.settleDate = settleDate;
	}

	/**
	 * @return the billMonth
	 */
	public Integer getBillMonth() {
		return billMonth;
	}

	/**
	 * @param billMonth the billMonth to set
	 */
	public void setBillMonth(Integer billMonth) {
		this.billMonth = billMonth;
	}
}